title: Anh-Thi Dinh
description: I failed my way to success
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# author's info, important for displaying info on site
author:
  name: Anh-Thi Dinh
  github: dinhanhthi
  facebook:
  email: dinhanhthi@gmail.com
  avatar: /img/avatar-icon.jpg
  real_avatar: /img/real_avatar.png
  ncb: 5 # number of challenge books

lang:
  current: en
  other_url:


title-separator: "-"

disqus:

google_analytics:

# Build settings
timezone: "Europe/Paris"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /:categories/:title
# paginate: 24
# paginate_path: "/thought/page-:num"

# Facebook App ID
fb_app_id: "1150663561751902"

sass:
  style: compact

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME

plugins:
  - jekyll-sitemap
  - jekyll-include-cache
